### PR TITLE
add project url for edirom online reloaded

### PR DESCRIPTION
**Pull request by krHERO**

### CODE REVIEW

**Review by daniel-jettka — COMMENTED** [review]
Thanks @krHERO That looks easy to review, but... where/how can I see the effect the change has?

**Comment by krHERO** [comment]
> Thanks @krHERO That looks easy to review, but... where/how can I see the effect the change has?

hi @daniel-jettka just follow the instructions in the readme. md "[How to build and develop](https://github.com/Edirom/ViFE-website?tab=readme-ov-file#how-to-build-and-develop)". that worked fine for me and i was able to see the changes and the link is working. thanks for taking care about the review.

**Comment by daniel-jettka** [comment]
> > Thanks @krHERO That looks easy to review, but... where/how can I see the effect the change has?
> 
> hi @daniel-jettka just follow the instructions in the readme. md "[How to build and develop](https://github.com/Edirom/ViFE-website?tab=readme-ov-file#how-to-build-and-develop)". that worked fine for me and i was able to see the changes and the link is working. thanks for taking care about the review.

Too obvious... :-)

**Review by daniel-jettka — APPROVED** [review]
Yes, looks good...

image

**Pull request merged**
