### PR TITLE
Blogpost Dennis Ried

### PR DESCRIPTION
**Pull request by riedde**
This PR contains the blog post for my "Who am I".
I already did the proof reading, but it won't be bad to have a second eye on it.

### CODE REVIEW

**Comment by riedde** [comment]
@DennisFriedl If the date needs to be changed, feel free to do it. Does not have any side-effects to the content.

**Comment by DennisFriedl** [comment]
@riedde I changed the grammatical gender of ViFE and created a teaser image that looks better for the small bar of the bootstrap card. Please tell me if you are okay with that.

**Comment by riedde** [comment]
Thank you @DennisFriedl

**Review by DennisFriedl — APPROVED** [review]
Nice! Will approve it then. Thank you very much @riedde. Your post will be visible on the 27th, that fits nicely because the post of Irmlind was just released on friday.

**Pull request merged**
